name: healthcare_symptom_checker_backend
description: Healthcare Symptom Checker Backend API
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.4
  http: ^1.1.0
  postgres: ^3.0.2
  uuid: ^4.2.1
  crypto: ^3.0.3
  dotenv: ^4.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.24.6
  shelf_test_handler: ^2.0.2
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0

executables:
  server:
